In [3]:
import numpy as np
y=np.array([11,4,5,14])
x=np.array([4,8,13,7])
X=(x-x.mean())/(x.std())
Y=(y-y.mean())/(y.std())
print(X)
print(Y)da

[-1.2344268  0.         1.5430335 -0.3086067]
[ 0.60192927 -1.08347268 -0.84270097  1.32424438]


In [4]:
std_data=np.column_stack((X,Y))
print(std_data)

[[-1.2344268   0.60192927]
 [ 0.         -1.08347268]
 [ 1.5430335  -0.84270097]
 [-0.3086067   1.32424438]]


In [5]:
c=np.cov(X,Y)
print("covariance matrix: ",c)

covariance matrix:  [[ 1.33333333 -0.81734138]
 [-0.81734138  1.33333333]]


In [6]:
values,vectors=np.linalg.eig(c)
print("Eigen Values: ",values)
print("Eigen values: ",vectors)

Eigen Values:  [2.15067471 0.51599195]
Eigen values:  [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [9]:
idx=np.argsort(values)[::-1]
values=values[idx]#sorting values
vectors=vectors[:,idx]
num_components=1
projection_matrix=vectors[:,num_components]
data_reduced=np.dot(std_data,projection_matrix)
data_reduced

array([-0.4472433 , -0.76613088,  0.49520988,  0.71816429])